### PR TITLE
Added 3 skills of mine

### PR DESCRIPTION
**Pull request by garimasingh128**
>## ✍&nbsp; Skills developed
- Cakewalk - A starter template for beginners
- Touristy - Tells info about tourist places of Australia
- Hello world - my hosted skill

### CODE REVIEW

**Comment by garimasingh128** [comment]
@tarunnsingh

**Comment by tarunnsingh** [comment]
Hey @garimasingh128 , please add according to these [guidelines](https://github.com/alexa-dev-hub/alexa-skills/blob/master/CONTRIBUTING.md). 
If you push the ZIP folder, then you'll be exposing your Skill IDs too.

**Comment by garimasingh128** [comment]
@tarunnsingh please check again and approve!

**Comment by tarunnsingh** [comment]
@garimasingh128 As mentioned in the guidelines, you are required to extract the contents from the zipped folder.
For example your cakewalk skill should be created as a folder here: 
**alexa-skills/skills-by-the-team/GarimaSingh/cakewalk** within which you have **assets, interactionModels, lambda** folders.

The Zipped Binary is not useful as its contents cannot be viewed directly on GitHub.
Please make these changes and PR will be approved.

**Comment by garimasingh128** [comment]
Ok sorry for bothering. I will update it.

**Pull request merged**
