### PR TITLE
@hactoberfest with alexa 

### PR DESCRIPTION
**Pull request by Neeraj2212**
Neeraj Patil
Patna Chapter
@hactoberfest with alexa
@tarunnsingh

### CODE REVIEW

**Comment by tarunnsingh** [comment]
@Neeraj2212 
Please do not simply copy and paste.
This Skill is Already there as a template [HERE](https://github.com/alexa-dev-hub/alexa-skill-guess-my-character).


You can add even any basic Skill which you have created.

**Comment by Neeraj2212** [comment]
@tarunnsingh I followed your Youtube video but when when you said to copy and paste that json i have done that that's why it looks same as you

**Comment by tarunnsingh** [comment]
@Neeraj2212 Yes I completely understand that, still by going through the code, I couldn't see any major differences of functionalities. Could you please brief on that in a **about_skill.md** file. 😄

**Review by tarunnsingh — COMMENTED** [review]
No response, thus closed.

**Pull request closed without merging**
